#!/usr/bin/env python
#
description = """\
A simple script to implement the password generation mechanism from \
http://xkcd.com/936/\
"""

import argparse
import math
import random
import re
import sys

# Parse arguments
parser = argparse.ArgumentParser(description=description)
parser.add_argument('wordfile', type=file, help='The word file')
parser.add_argument('-n', type=int, default=4,
                   help='Number of words to generate (default: 4)')

args = parser.parse_args()

# Read in the word list from standard input, and print out some stats
acceptable = re.compile(r'^[a-z]{4,}$')
words = {x for x in args.wordfile.read().split() if acceptable.match(x)}
numwords = len(words)
entropy = math.log(numwords, 2) * args.n

print('Picking {} of {} words, approximately {} bits of entropy'
      .format(args.n, numwords, entropy))

# Pick N words at random
print(' '.join(random.sample(words, args.n)))
